name: Dev - Python Build, Lint & Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            **/pyproject.toml
            **/poetry.lock
            **/pdm.lock
            **/uv.lock

      # # 3. Cache pip
      # - name: Cache pip
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      # 3. Install dependencies etc
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Tools needed to build distributions
          python -m pip install --upgrade build setuptools wheel
          pip install -e ".[ci]"
          pip install 'black[jupyter]'

      # 4. fix formatting with black
      # - name: Check code formatting with black
      #   run: |
      #     pip install black
      #     black --line-length 120 .
        # run: |
        #   pip install black
        #   black --line-length 120 .

      ## 5. Lint code with flake8
      #- name: Lint with flake8
      #  run: |
      #    pip install flake8
      #    flake8 --max-line-length=120 .

      # 6. Build package if applicable
      - name: Build package
        run: python -m build
        # run: |
        #   if [ -f setup.py ]; then python setup.py build; fi
        #   if [ -f pyproject.toml ]; then python -m build; fi

      # 7. Import check
      - name: Import check
        run: python -c "import sys; import os; print('Python OK')"

      # 9. Run tests if folder exists
      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pip install pytest && pytest; fi
